### ISSUE TITLE
error format_image_to_sce

### ISSUE THREAD

**Issue by Lan-h** [cancer-evolution/SPIAT#11]
Hi! Thank you for the package. 
Unfortunately, I haven't been able to import the data with format_image_to_sce. 
Here is the error message I get: 
`Error in `[.data.frame`(image, , c("Cell.ID", "Phenotype", "Cell.X.Position", : undefined columns selected`
Here is an overview of the kind of txt file I have: 
cell.ID Phenotype Cell.X.Position Cell.Y.Position Cell..CD3.mean  Cell..CD8.mean Cell..ker.mean Cell..nuclei.mean
       1     Strom          8488.3          211.77         0.8845           9.2829          14.3625        24.6056           59.3187

Do you know what is wrong in the data?

**Comment by mblue9** [comment]
I think it's expecting the column to be called Cell.ID not cell.ID. Could you change the column name in the input file to Cell.ID and see if that works?

**Comment by Lan-h** [comment]
it works thanks!

**Comment by mblue9** [comment]
Great 😄
